### PR TITLE
Storage pool provisioning with Ansible instead of Virtual Machine Manager GUI

### PR DESCRIPTION
**Pull request by manfredmuth**
# issue #6 related

https://github.com/disposab1e/okd-lab/issues/6

The storage pool default will be created in the system context.
```
Destination /okd_lab
```
Many things still hard coded. But in line with the defaults introduced by project team.

### CODE REVIEW

**Comment by disposab1e** [comment]
@manfredmuth Cool! I will come back to you when I had more time this week. So far many thx for your contribution!

**Comment by disposab1e** [comment]
@manfredmuth The default pool is available in my installation of CentOS. Did you install with my doxs or do you have your own libvirt installation?

**Comment by disposab1e** [comment]
@manfredmuth regarding vnc... there was a bug in my docs with the port. The vnc server is started automatically on localhost 5999. Why did you start it manually?

**Comment by manfredmuth** [comment]
> @manfredmuth The default pool is available in my installation of CentOS. Did you install with my doxs or do you have your own libvirt installation?

I used the standard Hetzner CentOS 7.8 install and folloowed the installation instructions in the documentation. But the default storage pool in context qemu:///system was not created by default.

**Comment by manfredmuth** [comment]
> @manfredmuth regarding vnc... there was a bug in my docs with the port. The vnc server is started automatically on localhost 5999. Why did you start it manually?

You are right. the vncserver was started by default. Seems I cured my homemade problems by starting it manually on a different port

**Comment by disposab1e** [comment]
@manfredmuth To be honest I installed it many times and the default pool was always in place. I wonder a little... perhaps it's created when starting the GUI application, what I always do?

**Comment by disposab1e** [comment]
When you install it with Hetzner.... do you choose "Linux" or "VNC" as installation type?

**Comment by disposab1e** [comment]
vnc is a little bit tricky... but when you do it **exactly** as documents all should work fine.

**Comment by manfredmuth** [comment]
> When you install it with Hetzner.... do you choose "Linux" or "VNC" as installation type?
I use the VNC option

**Comment by disposab1e** [comment]
And I'm sure:

Software Selection
    Virtualization Host
    Virtualization Platform
    System Administration Tools

**Comment by manfredmuth** [comment]
> And I'm sure:
> 
> Software Selection
> Virtualization Host
> Virtualization Platform
> System Administration Tools

Yes - exactly this ....

**Comment by disposab1e** [comment]
Ok... I try to reproduce...

**Comment by disposab1e** [comment]
Yes it's missing when you not start the GUI "Applications -> System Tools -> Virtual Machine Manager" what I have always done after a fresh installation.

**Comment by disposab1e** [comment]
I hope you don't mind! I have[ decided to document it](https://github.com/disposab1e/okd-lab/blob/release-0.0.4/docs/02_provision_infrastructure.md) instead of using your ansible files for the following reasons: 

- For the storage location it's easiest to use /var/lib/libvirt/images 
- But most imporatnt: I will migrate more and more of some ansible files to terraform (ses an example [here](https://github.com/samuelvl/ocp4-disconnected-lab))

I also fixed the wrong file pathes for sizing and your "It's" to "It is"  

All is done on the release-0.0.4 branch. I will switch to newest software and openshift versions on this branch too before I release a new version.

Anyway... it's a pleasure that you have used my small project and found this ugly bug!

Everything else was working for you out of the box?

**Comment by manfredmuth** [comment]
Fine - you are the boss!
Everything else is working

**Comment by disposab1e** [comment]
Great that everything else works for you. If you want to have some enhancements please let me know. I leave this pull request open for all others who want to go a different way than with the VMM GUI.

**Comment by disposab1e** [comment]
Time to close it...

**Pull request closed without merging**
